# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430f636a46b773d4b7ccbba35cd9f2187dcfd246307fc90faec37e05a10525be843d3a15f53620cb60c5f7151475fa8e59c0ae32c7d880ee327879cbde3cc306

test:
  secret_key_base: 9f7f75af15b89348cc4408401e7be3f1bd30e8e7c5b0a373a031e9435d304e1ee73051eca99ff3ba3e34adef9be037157035830ff913feaaa9e6c75da546edb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
